language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t aotarola/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aotarola/docker-react npm run test
